//! 行内图标表：`:name:` 的名字 → 显示内容。
//!
//! **解析层与调度器都不认识这张表。** `:rocket:` 在 AST 里只是一个
//! [`NodeKind::Icon`](crate::NodeKind::Icon)，查表、决定长什么样，都在渲染这一步。
//! 所以想把手搓 SVG 换进来、想加 `title`、想按主题换图标集，改这一个文件就够了。
//!
//! 图标与[行内调用](crate::NodeKind::InlineCall)是两件事：图标是**呈现**，认不
//! 认识决定它显示成图标还是原样文字；行内调用是**逻辑**，要展开器认领，没人认领
//! 就是错误。所以 `:smile:` 和 `{{smile}}` 不是一个东西。
//!
//! 目前表里是常用 emoji 短码的字符形式。未收录的名字不会被吞掉——渲染器会把
//! `:name:` 原样输出。

/// 查一个图标名。
pub(crate) fn value(alias: &str) -> Option<&'static str> {
    Some(match alias {
        // 表情
        "smile" => "😄",
        "smiley" => "😃",
        "grin" => "😁",
        "laughing" | "satisfied" => "😆",
        "sweat_smile" => "😅",
        "joy" => "😂",
        "rofl" => "🤣",
        "wink" => "😉",
        "blush" => "😊",
        "heart_eyes" => "😍",
        "kissing_heart" => "😘",
        "thinking" => "🤔",
        "neutral_face" => "😐",
        "expressionless" => "😑",
        "unamused" => "😒",
        "sweat" => "😓",
        "pensive" => "😔",
        "confused" => "😕",
        "upside_down_face" => "🙃",
        "smirk" => "😏",
        "sunglasses" => "😎",
        "cry" => "😢",
        "sob" => "😭",
        "angry" => "😠",
        "rage" => "😡",
        "scream" => "😱",
        "fearful" => "😨",
        "sleeping" => "😴",
        "mask" => "😷",
        "nauseated_face" => "🤢",
        "poop" | "hankey" => "💩",
        "skull" => "💀",
        "ghost" => "👻",
        "alien" => "👽",
        "robot" => "🤖",
        "see_no_evil" => "🙈",
        "hear_no_evil" => "🙉",
        "speak_no_evil" => "🙊",
        // 手势与人物
        "wave" => "👋",
        "thumbsup" | "+1" => "👍",
        "thumbsdown" | "-1" => "👎",
        "ok_hand" => "👌",
        "clap" => "👏",
        "pray" | "praying_hands" => "🙏",
        "muscle" => "💪",
        "point_right" => "👉",
        "point_left" => "👈",
        "point_up" => "☝️",
        "raised_hand" => "✋",
        "eyes" => "👀",
        "brain" => "🧠",
        "baby" => "👶",
        "boy" => "👦",
        "girl" => "👧",
        "man" => "👨",
        "woman" => "👩",
        "bow" => "🙇",
        "shrug" => "🤷",
        "facepalm" => "🤦",
        // 心与符号
        "heart" => "❤️",
        "broken_heart" => "💔",
        "yellow_heart" => "💛",
        "green_heart" => "💚",
        "blue_heart" => "💙",
        "purple_heart" => "💜",
        "black_heart" => "🖤",
        "sparkling_heart" => "💖",
        "star" => "⭐",
        "star2" => "🌟",
        "sparkles" => "✨",
        "zap" => "⚡",
        "boom" | "collision" => "💥",
        "fire" => "🔥",
        "snowflake" => "❄️",
        "rainbow" => "🌈",
        "sunny" => "☀️",
        "cloud" => "☁️",
        "droplet" => "💧",
        "ocean" => "🌊",
        "tada" => "🎉",
        "confetti_ball" => "🎊",
        "gift" => "🎁",
        "balloon" => "🎈",
        "trophy" => "🏆",
        "medal_sports" => "🏅",
        "crown" => "👑",
        "gem" => "💎",
        "moneybag" => "💰",
        "dollar" => "💵",
        "bulb" => "💡",
        "bell" => "🔔",
        "mega" => "📣",
        "loudspeaker" => "📢",
        "mag" => "🔍",
        "key" => "🔑",
        "lock" => "🔒",
        "unlock" => "🔓",
        "shield" => "🛡️",
        "hammer" => "🔨",
        "wrench" => "🔧",
        "gear" => "⚙️",
        "toolbox" => "🧰",
        "link" => "🔗",
        "paperclip" => "📎",
        "pushpin" => "📌",
        "round_pushpin" => "📍",
        "clipboard" => "📋",
        "memo" | "pencil" => "📝",
        "book" => "📕",
        "books" => "📚",
        "notebook" => "📓",
        "bookmark" => "🔖",
        "newspaper" => "📰",
        "email" | "envelope" => "✉️",
        "inbox_tray" => "📥",
        "outbox_tray" => "📤",
        "package" => "📦",
        "file_folder" => "📁",
        "open_file_folder" => "📂",
        "page_facing_up" => "📄",
        "calendar" => "📅",
        "date" => "📆",
        "clock1" | "clock" => "🕐",
        "hourglass" => "⌛",
        "alarm_clock" => "⏰",
        "computer" => "💻",
        "desktop_computer" => "🖥️",
        "keyboard" => "⌨️",
        "iphone" => "📱",
        "camera" => "📷",
        "video_camera" => "📹",
        "tv" => "📺",
        "battery" => "🔋",
        "floppy_disk" => "💾",
        "cd" => "💿",
        "satellite" => "📡",
        "wastebasket" => "🗑️",
        "rocket" => "🚀",
        "airplane" => "✈️",
        "car" => "🚗",
        "bus" => "🚌",
        "train" => "🚆",
        "ship" => "🚢",
        "bike" => "🚲",
        "walking" => "🚶",
        "runner" => "🏃",
        // 图表与状态
        "check" | "heavy_check_mark" | "white_check_mark" => "✅",
        "x" | "heavy_multiplication_x" => "❌",
        "o" | "heavy_circle" => "⭕",
        "warning" => "⚠️",
        "no_entry" => "⛔",
        "no_entry_sign" => "🚫",
        "question" => "❓",
        "exclamation" => "❗",
        "information_source" => "ℹ️",
        "bangbang" => "‼️",
        "interrobang" => "⁉️",
        "chart" | "bar_chart" => "📊",
        "chart_with_upwards_trend" | "trending_up" => "📈",
        "chart_with_downwards_trend" | "trending_down" => "📉",
        "crystal_ball" => "🔮",
        "recycle" => "♻️",
        "white_circle" => "⚪",
        "black_circle" => "⚫",
        "red_circle" => "🔴",
        "large_blue_circle" => "🔵",
        "small_blue_diamond" => "🔹",
        "small_orange_diamond" => "🔸",
        "arrow_right" => "➡️",
        "arrow_left" => "⬅️",
        "arrow_up" => "⬆️",
        "arrow_down" => "⬇️",
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_aliases_resolve() {
        assert_eq!(value("smile"), Some("😄"));
        assert_eq!(value("+1"), Some("👍"));
        assert_eq!(value("rocket"), Some("🚀"));
    }

    #[test]
    fn unknown_aliases_are_reported_as_missing() {
        assert_eq!(value("nope"), None);
        assert_eq!(value("30"), None);
        assert_eq!(value("Smile"), None);
    }
}
